### ISSUE TITLE
Forecasts are failing in 2021

### ISSUE THREAD

**Issue by jklukas** [mozilla/forecasting#39]
See https://workflow.telemetry.mozilla.org/tree?dag_id=kpi_forecasts

It looks like the simpleprophet logic has some assumption about running in 2020 that is now broken. I have toggled off the DAG for now, since it looks like it will continue to fail without intervention.

@xluo-ds Do we expect these forecasts to continue running in 2021? Do we expect there are modifications needed for 2021?

**Comment by xluo-ds** [comment]
Yes, Dan communicated with me that Selena wants to keep these forecast running in 2021. 

I will make a PR with the code update.

**Comment by jklukas** [comment]
This is fixed in https://github.com/mozilla/forecasting/pull/40 and I've verified that a few tasks were able to finish. I've cleared all the failed tasks and they should be fully complete in the next hour.
